{
  "name": "SupplyVisionPainel",
  "compatibilityLevel": 1606,
  "model": {
    "culture": "pt-BR",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "pt-BR",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "tables": [
      {
        "name": "Painel",
        "lineageTag": "09eb5dd3-1590-5c95-a9c3-2a95dd9e8a3c",
        "columns": [
          {
            "name": "Data",
            "dataType": "dateTime",
            "sourceColumn": "Data",
            "summarizeBy": "none",
            "lineageTag": "e477810a-d283-5143-8bab-19cf77b9534f",
            "formatString": "dd/mm/yyyy"
          },
          {
            "name": "OS",
            "dataType": "string",
            "sourceColumn": "OS",
            "summarizeBy": "none",
            "lineageTag": "1b389e8a-e7b6-58f2-ac34-3b6ffcfbcc27"
          },
          {
            "name": "Criador",
            "dataType": "string",
            "sourceColumn": "Criador",
            "summarizeBy": "none",
            "lineageTag": "17e57edd-0ee4-5d93-af1b-37142416d607"
          },
          {
            "name": "Cidade",
            "dataType": "string",
            "sourceColumn": "Cidade",
            "summarizeBy": "none",
            "lineageTag": "6f71ab0c-cf1e-57ab-bcb3-6b7142fac1fe"
          },
          {
            "name": "Fornecedor",
            "dataType": "string",
            "sourceColumn": "Fornecedor",
            "summarizeBy": "none",
            "lineageTag": "79fc1302-b2a9-5914-b9b4-2f2cee4225ee"
          },
          {
            "name": "Modelo",
            "dataType": "string",
            "sourceColumn": "Modelo",
            "summarizeBy": "none",
            "lineageTag": "4762f385-da62-521d-8569-f55a7c937199"
          },
          {
            "name": "Grupo Modelo",
            "dataType": "string",
            "sourceColumn": "Grupo Modelo",
            "summarizeBy": "none",
            "lineageTag": "ee0a7e97-5789-5021-80e7-712f01bc1780"
          },
          {
            "name": "Item",
            "dataType": "string",
            "sourceColumn": "Item",
            "summarizeBy": "none",
            "lineageTag": "8a1f5633-fe3c-59e0-a402-a7f29470baba"
          },
          {
            "name": "Grupo Item",
            "dataType": "string",
            "sourceColumn": "Grupo Item",
            "summarizeBy": "none",
            "lineageTag": "4ff7e603-60b6-567f-8895-85c21d3ad06a"
          },
          {
            "name": "Motivo Sem Acordo",
            "dataType": "string",
            "sourceColumn": "Motivo Sem Acordo",
            "summarizeBy": "none",
            "lineageTag": "958eacdf-2fc4-592f-86ae-fcb9e39da2d7"
          },
          {
            "name": "Tinha acordo?",
            "dataType": "string",
            "sourceColumn": "Tinha acordo?",
            "summarizeBy": "none",
            "lineageTag": "f0166095-0d38-571d-8bf4-3b90fcc4e7e4"
          },
          {
            "name": "Fornecedor do Acordo",
            "dataType": "string",
            "sourceColumn": "Fornecedor do Acordo",
            "summarizeBy": "none",
            "lineageTag": "08c17e9d-b19c-5672-a586-637fe8224582"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status",
            "summarizeBy": "none",
            "lineageTag": "9b96e65d-6eeb-5700-bdff-60192788f6cd"
          },
          {
            "name": "CNPJ",
            "dataType": "string",
            "sourceColumn": "CNPJ",
            "summarizeBy": "none",
            "lineageTag": "f575da17-07e5-5f55-9d81-7967c1263b2e"
          },
          {
            "name": "STATUS_ACORDO",
            "dataType": "string",
            "sourceColumn": "STATUS_ACORDO",
            "summarizeBy": "none",
            "lineageTag": "6113dd38-6470-5e9f-ba93-0eeeb72279f0"
          },
          {
            "name": "RUN_ID",
            "dataType": "string",
            "sourceColumn": "RUN_ID",
            "summarizeBy": "none",
            "lineageTag": "fc21360a-9898-56cc-badd-407fe09eef1d"
          },
          {
            "name": "Ano-Mes",
            "dataType": "string",
            "sourceColumn": "Ano-Mes",
            "summarizeBy": "none",
            "lineageTag": "cbb7bd97-7846-5d1f-97c2-2d0f42a41205"
          },
          {
            "name": "Mes",
            "dataType": "string",
            "sourceColumn": "Mes",
            "summarizeBy": "none",
            "lineageTag": "269f90d9-ea10-5a37-a11c-d41d00ba2005"
          },
          {
            "name": "Trimestre",
            "dataType": "string",
            "sourceColumn": "Trimestre",
            "summarizeBy": "none",
            "lineageTag": "d04c4cc8-b89b-5b9d-b80b-f52b15ec61ba"
          },
          {
            "name": "Mes Nome",
            "dataType": "string",
            "sourceColumn": "Mes Nome",
            "summarizeBy": "none",
            "lineageTag": "2851a87f-68a7-51e6-9892-ee5591c8bf59",
            "sortByColumn": "Mes Num"
          },
          {
            "name": "Ano",
            "dataType": "int64",
            "sourceColumn": "Ano",
            "summarizeBy": "none",
            "lineageTag": "354c0cfa-0350-552a-b21e-89e39d068e01",
            "formatString": "0"
          },
          {
            "name": "Mes Num",
            "dataType": "int64",
            "sourceColumn": "Mes Num",
            "summarizeBy": "none",
            "lineageTag": "13786026-981e-56c4-9e5b-00f49ae01453",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Ultimos 30 dias",
            "dataType": "boolean",
            "sourceColumn": "Ultimos 30 dias",
            "summarizeBy": "none",
            "lineageTag": "0299f5e3-fb15-502a-a2c4-114798d3cc90"
          },
          {
            "name": "Ultimos 365 dias",
            "dataType": "boolean",
            "sourceColumn": "Ultimos 365 dias",
            "summarizeBy": "none",
            "lineageTag": "83519ce8-2b06-56e6-9bfc-dc0f95cc5ebb"
          },
          {
            "name": "Mes Fechado",
            "dataType": "boolean",
            "sourceColumn": "Mes Fechado",
            "summarizeBy": "none",
            "lineageTag": "1005d227-93b2-5874-9ad0-2fd81b92b96e"
          },
          {
            "name": "Ultimos 12 meses fechados",
            "dataType": "boolean",
            "sourceColumn": "Ultimos 12 meses fechados",
            "summarizeBy": "none",
            "lineageTag": "548e25cd-c2fb-5d3b-a80f-0e30b2802249"
          },
          {
            "name": "Qtd",
            "dataType": "double",
            "sourceColumn": "Qtd",
            "summarizeBy": "sum",
            "lineageTag": "005b64c6-7a3c-50d8-9df8-f7f208c454d8",
            "formatString": "#,0.##"
          },
          {
            "name": "Preco OS",
            "dataType": "double",
            "sourceColumn": "Preco OS",
            "summarizeBy": "sum",
            "lineageTag": "aceb274d-ffe6-5b27-a5cc-8b40a3ab2971",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "Preco Acordo",
            "dataType": "double",
            "sourceColumn": "Preco Acordo",
            "summarizeBy": "sum",
            "lineageTag": "2a5f2c6f-8d55-5b12-88f5-25860baaf7cd",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "Preco Total OS",
            "dataType": "double",
            "sourceColumn": "Preco Total OS",
            "summarizeBy": "sum",
            "lineageTag": "038f37bf-e769-5eca-a1ff-7aca0630f80f",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "Preco Total Acordo",
            "dataType": "double",
            "sourceColumn": "Preco Total Acordo",
            "summarizeBy": "sum",
            "lineageTag": "c7f5bf4f-a95e-52e3-a1d8-b93249db2f32",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "Diferenca Unit.",
            "dataType": "double",
            "sourceColumn": "Diferenca Unit.",
            "summarizeBy": "sum",
            "lineageTag": "7f91307f-5b5a-5b0a-91e3-aa13a062520b",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "Diferenca Total",
            "dataType": "double",
            "sourceColumn": "Diferenca Total",
            "summarizeBy": "sum",
            "lineageTag": "a1c8a37a-de56-53be-8d9c-3e39a47730db",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "Menor Preco Acordo",
            "dataType": "double",
            "sourceColumn": "Menor Preco Acordo",
            "summarizeBy": "sum",
            "lineageTag": "839ed315-3103-5e5d-a19a-33cf2787e1c4",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "Dif. p/ Menor Acordo",
            "dataType": "double",
            "sourceColumn": "Dif. p/ Menor Acordo",
            "summarizeBy": "sum",
            "lineageTag": "0165fdc3-5bb6-545d-9817-59662be3f5b4",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "DATA_EXECUCAO",
            "dataType": "dateTime",
            "sourceColumn": "DATA_EXECUCAO",
            "summarizeBy": "none",
            "lineageTag": "068565cb-025b-55f6-9270-ceeec64833c6",
            "formatString": "dd/mm/yyyy hh:nn",
            "isHidden": true
          }
        ],
        "measures": [
          {
            "name": "Valor Total",
            "expression": "SUM('Painel'[Preco Total OS])",
            "lineageTag": "96c31c36-8bd9-51e6-bd2b-23c65333a6fd",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "Linhas",
            "expression": "COUNTROWS('Painel')",
            "lineageTag": "8c243e69-91ce-50bf-aa49-8cf0b2bf4ade",
            "formatString": "#,0"
          },
          {
            "name": "Valor Fora do Acordo",
            "expression": "CALCULATE([Valor Total], 'Painel'[STATUS_ACORDO] = \"SEM_ACORDO\")",
            "lineageTag": "2bfc07d4-4d03-56c2-b8bb-621d7f0a3bd9",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "Valor Dentro do Acordo",
            "expression": "CALCULATE([Valor Total], 'Painel'[STATUS_ACORDO] = \"COM_ACORDO\")",
            "lineageTag": "546f99c8-e2a0-5149-ad28-fc7a4514ee2a",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "% Fora do Acordo",
            "expression": "DIVIDE([Valor Fora do Acordo], [Valor Total])",
            "lineageTag": "49b2f71e-8507-50c1-80d8-71d9630136f4",
            "formatString": "0.0%"
          },
          {
            "name": "Valor em Fuga",
            "expression": "CALCULATE([Valor Total], 'Painel'[STATUS_ACORDO] = \"SEM_ACORDO\", 'Painel'[Tinha acordo?] = \"SIM\")",
            "lineageTag": "26e515fa-c653-54f4-b66a-485830781f01",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "Valor Fora Sem Alternativa",
            "expression": "[Valor Fora do Acordo] - [Valor em Fuga]",
            "lineageTag": "d910d05a-09ff-5496-a305-f516ee7e3fde",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "Valor Acima do Acordo",
            "expression": "CALCULATE(SUM('Painel'[Diferenca Total]), 'Painel'[Status] = \"ACIMA DO ACORDO\")",
            "lineageTag": "213d6114-f87b-5080-b268-a1477f7ef0ad",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "Valor Abaixo do Acordo",
            "expression": "CALCULATE(SUM('Painel'[Diferenca Total]), 'Painel'[Status] = \"ABAIXO DO ACORDO\")",
            "lineageTag": "dc2338c1-9496-54e2-af33-2920158c75b7",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "% Acima",
            "expression": "DIVIDE(CALCULATE([Valor Total], 'Painel'[Status] = \"ACIMA DO ACORDO\"), [Valor Dentro do Acordo])",
            "lineageTag": "c8b0e991-6278-5f17-9a1c-871655cd6c47",
            "formatString": "0.0%"
          },
          {
            "name": "% Conforme",
            "expression": "DIVIDE(CALCULATE([Valor Total], 'Painel'[Status] = \"CONFORME\"), [Valor Dentro do Acordo])",
            "lineageTag": "0a97840f-44b5-5ed4-ae6a-03ac68f816db",
            "formatString": "0.0%"
          },
          {
            "name": "% Abaixo",
            "expression": "DIVIDE(CALCULATE([Valor Total], 'Painel'[Status] = \"ABAIXO DO ACORDO\"), [Valor Dentro do Acordo])",
            "lineageTag": "943a8286-4ed4-5130-9592-8059e9cb8e1c",
            "formatString": "0.0%"
          },
          {
            "name": "Janela 30d",
            "expression": "VAR Fim = CALCULATE(MAX('Painel'[Data]), ALL('Painel')) RETURN FORMAT(Fim - 29, \"dd/mm/yyyy\") & \" a \" & FORMAT(Fim, \"dd/mm/yyyy\")",
            "lineageTag": "0f5fda7e-98c0-5e6c-8a11-c1e7bce20def"
          },
          {
            "name": "Janela 365d",
            "expression": "VAR Fim = CALCULATE(MAX('Painel'[Data]), ALL('Painel')) RETURN FORMAT(Fim - 364, \"dd/mm/yyyy\") & \" a \" & FORMAT(Fim, \"dd/mm/yyyy\")",
            "lineageTag": "a9f3dd5d-f445-5001-9dd7-b0fe760ab37c"
          },
          {
            "name": "Valor Coberto 30d",
            "expression": "VAR Fim = CALCULATE(MAX('Painel'[Data]), ALL('Painel')) RETURN CALCULATE([Valor Total], ALL('Painel'), 'Painel'[Data] >= Fim - 29, 'Painel'[Data] <= Fim, 'Painel'[STATUS_ACORDO] = \"COM_ACORDO\")",
            "lineageTag": "783d4d63-49ed-5618-bf75-8ebd09653b74",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "% Acima 30d",
            "expression": "VAR Fim = CALCULATE(MAX('Painel'[Data]), ALL('Painel')) VAR Acima = CALCULATE([Valor Total], ALL('Painel'), 'Painel'[Data] >= Fim - 29, 'Painel'[Data] <= Fim, 'Painel'[Status] = \"ACIMA DO ACORDO\") RETURN DIVIDE(Acima, [Valor Coberto 30d])",
            "lineageTag": "e590e9c0-d78a-59cb-a736-aa8f22c394de",
            "formatString": "0.0%"
          },
          {
            "name": "% Conforme 30d",
            "expression": "VAR Fim = CALCULATE(MAX('Painel'[Data]), ALL('Painel')) VAR Conf = CALCULATE([Valor Total], ALL('Painel'), 'Painel'[Data] >= Fim - 29, 'Painel'[Data] <= Fim, 'Painel'[Status] = \"CONFORME\") RETURN DIVIDE(Conf, [Valor Coberto 30d])",
            "lineageTag": "3ea90a08-8048-5952-91e3-8f9238923153",
            "formatString": "0.0%"
          },
          {
            "name": "% Abaixo 30d",
            "expression": "VAR Fim = CALCULATE(MAX('Painel'[Data]), ALL('Painel')) VAR Ab = CALCULATE([Valor Total], ALL('Painel'), 'Painel'[Data] >= Fim - 29, 'Painel'[Data] <= Fim, 'Painel'[Status] = \"ABAIXO DO ACORDO\") RETURN DIVIDE(Ab, [Valor Coberto 30d])",
            "lineageTag": "eb4d18d6-6e2a-5ed9-b62f-0c8d1fddca7e",
            "formatString": "0.0%"
          },
          {
            "name": "Excedente Acima 30d",
            "expression": "VAR Fim = CALCULATE(MAX('Painel'[Data]), ALL('Painel')) RETURN CALCULATE(SUM('Painel'[Diferenca Total]), ALL('Painel'), 'Painel'[Data] >= Fim - 29, 'Painel'[Data] <= Fim, 'Painel'[Status] = \"ACIMA DO ACORDO\")",
            "lineageTag": "4b1604ec-e540-59da-99fe-6def5c651e12",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "Valor Total 30d",
            "expression": "VAR Fim = CALCULATE(MAX('Painel'[Data]), ALL('Painel')) RETURN CALCULATE([Valor Total], ALL('Painel'), 'Painel'[Data] >= Fim - 29, 'Painel'[Data] <= Fim)",
            "lineageTag": "bf4032fb-7525-5299-91a6-e29fddde6484",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "Valor Total 365d",
            "expression": "VAR Fim = CALCULATE(MAX('Painel'[Data]), ALL('Painel')) RETURN CALCULATE([Valor Total], ALL('Painel'), 'Painel'[Data] >= Fim - 364, 'Painel'[Data] <= Fim)",
            "lineageTag": "1ca20805-c6ae-5c51-b320-86418e180977",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "Valor Fora do Acordo 30d",
            "expression": "VAR Fim = CALCULATE(MAX('Painel'[Data]), ALL('Painel')) RETURN CALCULATE([Valor Total], ALL('Painel'), 'Painel'[Data] >= Fim - 29, 'Painel'[Data] <= Fim, 'Painel'[STATUS_ACORDO] = \"SEM_ACORDO\")",
            "lineageTag": "d5cbdf55-44c2-5f9a-813c-b2ddfee3730f",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "% Fora do Acordo 30d",
            "expression": "DIVIDE([Valor Fora do Acordo 30d], [Valor Total 30d])",
            "lineageTag": "e2a05386-ce4e-55a8-82aa-6a29e545266f",
            "formatString": "0.0%"
          },
          {
            "name": "Valor em Fuga 365d",
            "expression": "VAR Fim = CALCULATE(MAX('Painel'[Data]), ALL('Painel')) RETURN CALCULATE([Valor Total], ALL('Painel'), 'Painel'[Data] >= Fim - 364, 'Painel'[Data] <= Fim, 'Painel'[STATUS_ACORDO] = \"SEM_ACORDO\", 'Painel'[Tinha acordo?] = \"SIM\")",
            "lineageTag": "3ff20baa-d9a6-5f44-b10d-18b88fcfac54",
            "formatString": "\"R$\" #,0.00"
          },
          {
            "name": "% em Fuga 365d",
            "expression": "DIVIDE([Valor em Fuga 365d], [Valor Total 365d])",
            "lineageTag": "a60c4f22-3390-511f-9e2c-7910938be493",
            "formatString": "0.0%"
          },
          {
            "name": "Fornecedores",
            "expression": "DISTINCTCOUNT('Painel'[Fornecedor])",
            "lineageTag": "9162b21f-c433-5730-939d-0fccaf35d61b",
            "formatString": "#,0"
          },
          {
            "name": "Cidades",
            "expression": "DISTINCTCOUNT('Painel'[Cidade])",
            "lineageTag": "ff8077fd-974e-58e1-9ec5-089209fcf8e3",
            "formatString": "#,0"
          },
          {
            "name": "Itens",
            "expression": "DISTINCTCOUNT('Painel'[Grupo Item])",
            "lineageTag": "5e1af8b6-6079-511a-ad9b-9cdb2563e5bf",
            "formatString": "#,0"
          },
          {
            "name": "Modelos",
            "expression": "DISTINCTCOUNT('Painel'[Grupo Modelo])",
            "lineageTag": "f471d0f8-2568-562a-ba58-b4930b52d3f8",
            "formatString": "#,0"
          },
          {
            "name": "% do Fora do Acordo",
            "expression": "DIVIDE([Valor Fora do Acordo], CALCULATE([Valor Fora do Acordo], ALLSELECTED()))",
            "lineageTag": "e9e270d8-661c-59f0-952e-4a32452d919f",
            "formatString": "0.0%"
          },
          {
            "name": "Ultima Execucao",
            "expression": "MAX('Painel'[DATA_EXECUCAO])",
            "lineageTag": "5ccbcb8c-caae-5d53-9548-7750f8f7dcf5",
            "formatString": "dd/mm/yyyy hh:nn"
          }
        ],
        "partitions": [
          {
            "name": "Painel",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Fonte = Parquet.Document(File.Contents(\"C:\\Projetos\\supply-vision\\painel\\consolidado\\supply_vision_painel.parquet\")),",
                "    Tipos = Table.TransformColumnTypes(Fonte, {{\"Data\", type date}}),",
                "    ComAno = Table.AddColumn(Tipos, \"Ano\", each Date.Year([Data]), Int64.Type),",
                "    ComAnoMes = Table.AddColumn(ComAno, \"Ano-Mes\", each Date.ToText([Data], [Format=\"yyyy-MM\"]), type text),",
                "    ComMes = Table.AddColumn(ComAnoMes, \"Mes\", each Date.ToText([Data], [Format=\"MMM/yy\", Culture=\"pt-BR\"]), type text),",
                "    ComMesNum = Table.AddColumn(ComMes, \"Mes Num\", each Date.Month([Data]), Int64.Type),",
                "    ComMesNome = Table.AddColumn(ComMesNum, \"Mes Nome\", each Date.ToText([Data], [Format=\"MMMM\", Culture=\"pt-BR\"]), type text),",
                "    ComTrimestre = Table.AddColumn(ComMesNome, \"Trimestre\", each \"T\" & Text.From(Date.QuarterOfYear([Data])) & \"/\" & Text.From(Date.Year([Data])), type text),",
                "    // Janela de 30 dias ancorada na data mais recente da BASE, nao em",
                "    // DateTime.LocalNow(): assim a pagina de conformidade e as medidas de 30",
                "    // dias usam exatamente o mesmo recorte, e um refresh atrasado nao esvazia",
                "    // a pagina -- ela passa a mostrar os ultimos 30 dias que existem no dado.",
                "    Fim = List.Max(ComTrimestre[Data]),",
                "    ComJanela = Table.AddColumn(ComTrimestre, \"Ultimos 30 dias\", each [Data] >= Date.AddDays(Fim, -29), type logical),",
                "    // 365 dias para a fuga de contrato: sem vigencia na ACORDOS.xlsx, uma",
                "    // compra de 2025 que hoje casa com um acordo pode nao ter tido acordo",
                "    // naquela data. Um ano limita o quanto o catalogo de acordos mudou.",
                "    ComJanelaAno = Table.AddColumn(ComJanela, \"Ultimos 365 dias\", each [Data] >= Date.AddDays(Fim, -364), type logical),",
                "    // O mes corrente esta sempre incompleto: em 13/08/2026 agosto tem 12 dias,",
                "    // e a coluna cai a ~40% das outras em qualquer grafico mensal. Isso le como",
                "    // queda de gasto, que nao houve. Todo grafico com Ano-Mes no eixo filtra por",
                "    // \"Mes Fechado\" para nao mostrar um mes que ainda esta acontecendo.",
                "    InicioMesFim = Date.StartOfMonth(Fim),",
                "    ComMesFechado = Table.AddColumn(ComJanelaAno, \"Mes Fechado\", each [Data] < InicioMesFim, type logical),",
                "    // Doze meses fechados: a janela de 365 dias corta o mes inicial no meio",
                "    // (comeca em 13/08/2025), entao o primeiro mes do grafico tambem aparecia",
                "    // pela metade. Esta coluna pega meses inteiros nas duas pontas.",
                "    Inicio12 = Date.AddMonths(InicioMesFim, -12),",
                "    Com12Meses = Table.AddColumn(ComMesFechado, \"Ultimos 12 meses fechados\",",
                "        each [Data] >= Inicio12 and [Data] < InicioMesFim, type logical)",
                "in",
                "    Com12Meses"
              ]
            }
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Painel\"]"
      }
    ]
  }
}