{
  "compatibilityLevel": 1606,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Painel\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "efa25163-ba24-40c1-a233-37c801b6e366",
        "fromColumn": "Data",
        "fromTable": "Painel",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e147814c-e9aa-4a3c-9e3d-9b87ada1b76c"
      },
      {
        "name": "0e79db95-0402-4da1-8c57-dcf0c4401fbc",
        "fromColumn": "DATA_EXECUCAO",
        "fromTable": "Painel",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e2659a95-d933-433a-b43d-737ef1a03d8f"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "Painel",
        "columns": [
          {
            "name": "Data",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "e477810a-d283-5143-8bab-19cf77b9534f",
            "sourceColumn": "Data",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_e147814c-e9aa-4a3c-9e3d-9b87ada1b76c"
                },
                "isDefault": true,
                "relationship": "efa25163-ba24-40c1-a233-37c801b6e366"
              }
            ]
          },
          {
            "name": "OS",
            "dataType": "string",
            "lineageTag": "1b389e8a-e7b6-58f2-ac34-3b6ffcfbcc27",
            "sourceColumn": "OS",
            "summarizeBy": "none"
          },
          {
            "name": "Criador",
            "dataType": "string",
            "lineageTag": "17e57edd-0ee4-5d93-af1b-37142416d607",
            "sourceColumn": "Criador",
            "summarizeBy": "none"
          },
          {
            "name": "Cidade",
            "dataType": "string",
            "lineageTag": "6f71ab0c-cf1e-57ab-bcb3-6b7142fac1fe",
            "sourceColumn": "Cidade",
            "summarizeBy": "none"
          },
          {
            "name": "Fornecedor",
            "dataType": "string",
            "lineageTag": "79fc1302-b2a9-5914-b9b4-2f2cee4225ee",
            "sourceColumn": "Fornecedor",
            "summarizeBy": "none"
          },
          {
            "name": "Modelo",
            "dataType": "string",
            "lineageTag": "4762f385-da62-521d-8569-f55a7c937199",
            "sourceColumn": "Modelo",
            "summarizeBy": "none"
          },
          {
            "name": "Item",
            "dataType": "string",
            "lineageTag": "8a1f5633-fe3c-59e0-a402-a7f29470baba",
            "sourceColumn": "Item",
            "summarizeBy": "none"
          },
          {
            "name": "Motivo Sem Acordo",
            "dataType": "string",
            "lineageTag": "958eacdf-2fc4-592f-86ae-fcb9e39da2d7",
            "sourceColumn": "Motivo Sem Acordo",
            "summarizeBy": "none"
          },
          {
            "name": "Tinha acordo?",
            "dataType": "string",
            "lineageTag": "f0166095-0d38-571d-8bf4-3b90fcc4e7e4",
            "sourceColumn": "Tinha acordo?",
            "summarizeBy": "none"
          },
          {
            "name": "Fornecedor do Acordo",
            "dataType": "string",
            "lineageTag": "08c17e9d-b19c-5672-a586-637fe8224582",
            "sourceColumn": "Fornecedor do Acordo",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "dataType": "string",
            "lineageTag": "9b96e65d-6eeb-5700-bdff-60192788f6cd",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "CNPJ",
            "dataType": "string",
            "lineageTag": "f575da17-07e5-5f55-9d81-7967c1263b2e",
            "sourceColumn": "CNPJ",
            "summarizeBy": "none"
          },
          {
            "name": "STATUS_ACORDO",
            "dataType": "string",
            "lineageTag": "6113dd38-6470-5e9f-ba93-0eeeb72279f0",
            "sourceColumn": "STATUS_ACORDO",
            "summarizeBy": "none"
          },
          {
            "name": "RUN_ID",
            "dataType": "string",
            "lineageTag": "fc21360a-9898-56cc-badd-407fe09eef1d",
            "sourceColumn": "RUN_ID",
            "summarizeBy": "none"
          },
          {
            "name": "Ano-Mes",
            "dataType": "string",
            "lineageTag": "cbb7bd97-7846-5d1f-97c2-2d0f42a41205",
            "sourceColumn": "Ano-Mes",
            "summarizeBy": "none"
          },
          {
            "name": "Mes",
            "dataType": "string",
            "lineageTag": "269f90d9-ea10-5a37-a11c-d41d00ba2005",
            "sourceColumn": "Mes",
            "summarizeBy": "none"
          },
          {
            "name": "Trimestre",
            "dataType": "string",
            "lineageTag": "d04c4cc8-b89b-5b9d-b80b-f52b15ec61ba",
            "sourceColumn": "Trimestre",
            "summarizeBy": "none"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "354c0cfa-0350-552a-b21e-89e39d068e01",
            "sourceColumn": "Ano",
            "summarizeBy": "sum"
          },
          {
            "name": "Qtd",
            "dataType": "double",
            "formatString": "#,0.##",
            "lineageTag": "005b64c6-7a3c-50d8-9df8-f7f208c454d8",
            "sourceColumn": "Qtd",
            "summarizeBy": "sum"
          },
          {
            "name": "Preco OS",
            "dataType": "double",
            "formatString": "\"R$\" #,0.00",
            "lineageTag": "aceb274d-ffe6-5b27-a5cc-8b40a3ab2971",
            "sourceColumn": "Preco OS",
            "summarizeBy": "sum"
          },
          {
            "name": "Preco Acordo",
            "dataType": "double",
            "formatString": "\"R$\" #,0.00",
            "lineageTag": "2a5f2c6f-8d55-5b12-88f5-25860baaf7cd",
            "sourceColumn": "Preco Acordo",
            "summarizeBy": "sum"
          },
          {
            "name": "Preco Total OS",
            "dataType": "double",
            "formatString": "\"R$\" #,0.00",
            "lineageTag": "038f37bf-e769-5eca-a1ff-7aca0630f80f",
            "sourceColumn": "Preco Total OS",
            "summarizeBy": "sum"
          },
          {
            "name": "Preco Total Acordo",
            "dataType": "double",
            "formatString": "\"R$\" #,0.00",
            "lineageTag": "c7f5bf4f-a95e-52e3-a1d8-b93249db2f32",
            "sourceColumn": "Preco Total Acordo",
            "summarizeBy": "sum"
          },
          {
            "name": "Diferenca Unit.",
            "dataType": "double",
            "formatString": "\"R$\" #,0.00",
            "lineageTag": "7f91307f-5b5a-5b0a-91e3-aa13a062520b",
            "sourceColumn": "Diferenca Unit.",
            "summarizeBy": "sum"
          },
          {
            "name": "Diferenca Total",
            "dataType": "double",
            "formatString": "\"R$\" #,0.00",
            "lineageTag": "a1c8a37a-de56-53be-8d9c-3e39a47730db",
            "sourceColumn": "Diferenca Total",
            "summarizeBy": "sum"
          },
          {
            "name": "Menor Preco Acordo",
            "dataType": "double",
            "formatString": "\"R$\" #,0.00",
            "lineageTag": "839ed315-3103-5e5d-a19a-33cf2787e1c4",
            "sourceColumn": "Menor Preco Acordo",
            "summarizeBy": "sum"
          },
          {
            "name": "Dif. p/ Menor Acordo",
            "dataType": "double",
            "formatString": "\"R$\" #,0.00",
            "lineageTag": "0165fdc3-5bb6-545d-9817-59662be3f5b4",
            "sourceColumn": "Dif. p/ Menor Acordo",
            "summarizeBy": "sum"
          },
          {
            "name": "DATA_EXECUCAO",
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy hh:nn",
            "isHidden": true,
            "lineageTag": "068565cb-025b-55f6-9270-ceeec64833c6",
            "sourceColumn": "DATA_EXECUCAO",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_e2659a95-d933-433a-b43d-737ef1a03d8f"
                },
                "isDefault": true,
                "relationship": "0e79db95-0402-4da1-8c57-dcf0c4401fbc"
              }
            ]
          },
          {
            "name": "Grupo Modelo",
            "dataType": "string",
            "lineageTag": "ee0a7e97-5789-5021-80e7-712f01bc1780",
            "sourceColumn": "Grupo Modelo",
            "summarizeBy": "none"
          },
          {
            "name": "Grupo Item",
            "dataType": "string",
            "lineageTag": "4ff7e603-60b6-567f-8895-85c21d3ad06a",
            "sourceColumn": "Grupo Item",
            "summarizeBy": "none"
          },
          {
            "name": "Mes Nome",
            "dataType": "string",
            "lineageTag": "2851a87f-68a7-51e6-9892-ee5591c8bf59",
            "sortByColumn": "Mes Num",
            "sourceColumn": "Mes Nome",
            "summarizeBy": "none"
          },
          {
            "name": "Mes Num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "13786026-981e-56c4-9e5b-00f49ae01453",
            "sourceColumn": "Mes Num",
            "summarizeBy": "sum"
          },
          {
            "name": "Ultimos 30 dias",
            "dataType": "boolean",
            "lineageTag": "0299f5e3-fb15-502a-a2c4-114798d3cc90",
            "sourceColumn": "Ultimos 30 dias",
            "summarizeBy": "none"
          },
          {
            "name": "Ultimos 365 dias",
            "dataType": "boolean",
            "lineageTag": "83519ce8-2b06-56e6-9bfc-dc0f95cc5ebb",
            "sourceColumn": "Ultimos 365 dias",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "09eb5dd3-1590-5c95-a9c3-2a95dd9e8a3c",
        "measures": [
          {
            "name": "Valor Total",
            "expression": "SUM('Painel'[Preco Total OS])",
            "formatString": "\"R$\" #,0.00",
            "lineageTag": "96c31c36-8bd9-51e6-bd2b-23c65333a6fd"
          },
          {
            "name": "Linhas",
            "expression": "COUNTROWS('Painel')",
            "formatString": "#,0",
            "lineageTag": "8c243e69-91ce-50bf-aa49-8cf0b2bf4ade"
          },
          {
            "name": "Valor Fora do Acordo",
            "expression": "CALCULATE([Valor Total], 'Painel'[STATUS_ACORDO] = \"SEM_ACORDO\")",
            "formatString": "\"R$\" #,0.00",
            "lineageTag": "2bfc07d4-4d03-56c2-b8bb-621d7f0a3bd9"
          },
          {
            "name": "Valor Dentro do Acordo",
            "expression": "CALCULATE([Valor Total], 'Painel'[STATUS_ACORDO] = \"COM_ACORDO\")",
            "formatString": "\"R$\" #,0.00",
            "lineageTag": "546f99c8-e2a0-5149-ad28-fc7a4514ee2a"
          },
          {
            "name": "% Fora do Acordo",
            "expression": "DIVIDE([Valor Fora do Acordo], [Valor Total])",
            "formatString": "0.0%",
            "lineageTag": "49b2f71e-8507-50c1-80d8-71d9630136f4"
          },
          {
            "name": "Valor Acima do Acordo",
            "expression": "CALCULATE(SUM('Painel'[Diferenca Total]), 'Painel'[Status] = \"ACIMA DO ACORDO\")",
            "formatString": "\"R$\" #,0.00",
            "lineageTag": "213d6114-f87b-5080-b268-a1477f7ef0ad"
          },
          {
            "name": "Valor Abaixo do Acordo",
            "expression": "CALCULATE(SUM('Painel'[Diferenca Total]), 'Painel'[Status] = \"ABAIXO DO ACORDO\")",
            "formatString": "\"R$\" #,0.00",
            "lineageTag": "dc2338c1-9496-54e2-af33-2920158c75b7"
          },
          {
            "name": "Fornecedores",
            "expression": "DISTINCTCOUNT('Painel'[Fornecedor])",
            "formatString": "#,0",
            "lineageTag": "9162b21f-c433-5730-939d-0fccaf35d61b"
          },
          {
            "name": "Cidades",
            "expression": "DISTINCTCOUNT('Painel'[Cidade])",
            "formatString": "#,0",
            "lineageTag": "ff8077fd-974e-58e1-9ec5-089209fcf8e3"
          },
          {
            "name": "Itens",
            "expression": "DISTINCTCOUNT('Painel'[Grupo Item])",
            "formatString": "#,0",
            "lineageTag": "5e1af8b6-6079-511a-ad9b-9cdb2563e5bf"
          },
          {
            "name": "Modelos",
            "expression": "DISTINCTCOUNT('Painel'[Grupo Modelo])",
            "formatString": "#,0",
            "lineageTag": "f471d0f8-2568-562a-ba58-b4930b52d3f8"
          },
          {
            "name": "Ultima Execucao",
            "expression": "MAX('Painel'[DATA_EXECUCAO])",
            "formatString": "dd/mm/yyyy hh:nn",
            "lineageTag": "5ccbcb8c-caae-5d53-9548-7750f8f7dcf5"
          },
          {
            "name": "% do Fora do Acordo",
            "expression": "DIVIDE([Valor Fora do Acordo], CALCULATE([Valor Fora do Acordo], ALLSELECTED()))",
            "formatString": "0.0%",
            "lineageTag": "e9e270d8-661c-59f0-952e-4a32452d919f"
          },
          {
            "name": "Valor em Fuga",
            "expression": "CALCULATE([Valor Total], 'Painel'[STATUS_ACORDO] = \"SEM_ACORDO\", 'Painel'[Tinha acordo?] = \"SIM\")",
            "formatString": "\"R$\" #,0.00",
            "lineageTag": "26e515fa-c653-54f4-b66a-485830781f01"
          },
          {
            "name": "Valor Fora Sem Alternativa",
            "expression": "[Valor Fora do Acordo] - [Valor em Fuga]",
            "formatString": "\"R$\" #,0.00",
            "lineageTag": "d910d05a-09ff-5496-a305-f516ee7e3fde"
          },
          {
            "name": "% Acima",
            "expression": "DIVIDE(CALCULATE([Valor Total], 'Painel'[Status] = \"ACIMA DO ACORDO\"), [Valor Dentro do Acordo])",
            "formatString": "0.0%",
            "lineageTag": "c8b0e991-6278-5f17-9a1c-871655cd6c47"
          },
          {
            "name": "% Conforme",
            "expression": "DIVIDE(CALCULATE([Valor Total], 'Painel'[Status] = \"CONFORME\"), [Valor Dentro do Acordo])",
            "formatString": "0.0%",
            "lineageTag": "0a97840f-44b5-5ed4-ae6a-03ac68f816db"
          },
          {
            "name": "% Abaixo",
            "expression": "DIVIDE(CALCULATE([Valor Total], 'Painel'[Status] = \"ABAIXO DO ACORDO\"), [Valor Dentro do Acordo])",
            "formatString": "0.0%",
            "lineageTag": "943a8286-4ed4-5130-9592-8059e9cb8e1c"
          },
          {
            "name": "Janela 30d",
            "expression": "VAR Fim = CALCULATE(MAX('Painel'[Data]), ALL('Painel')) RETURN FORMAT(Fim - 29, \"dd/mm/yyyy\") & \" a \" & FORMAT(Fim, \"dd/mm/yyyy\")",
            "lineageTag": "0f5fda7e-98c0-5e6c-8a11-c1e7bce20def"
          },
          {
            "name": "Janela 365d",
            "expression": "VAR Fim = CALCULATE(MAX('Painel'[Data]), ALL('Painel')) RETURN FORMAT(Fim - 364, \"dd/mm/yyyy\") & \" a \" & FORMAT(Fim, \"dd/mm/yyyy\")",
            "lineageTag": "a9f3dd5d-f445-5001-9dd7-b0fe760ab37c"
          },
          {
            "name": "Valor Coberto 30d",
            "expression": "VAR Fim = CALCULATE(MAX('Painel'[Data]), ALL('Painel')) RETURN CALCULATE([Valor Total], ALL('Painel'), 'Painel'[Data] >= Fim - 29, 'Painel'[Data] <= Fim, 'Painel'[STATUS_ACORDO] = \"COM_ACORDO\")",
            "formatString": "\"R$\" #,0.00",
            "lineageTag": "783d4d63-49ed-5618-bf75-8ebd09653b74"
          },
          {
            "name": "% Acima 30d",
            "expression": "VAR Fim = CALCULATE(MAX('Painel'[Data]), ALL('Painel')) VAR Acima = CALCULATE([Valor Total], ALL('Painel'), 'Painel'[Data] >= Fim - 29, 'Painel'[Data] <= Fim, 'Painel'[Status] = \"ACIMA DO ACORDO\") RETURN DIVIDE(Acima, [Valor Coberto 30d])",
            "formatString": "0.0%",
            "lineageTag": "e590e9c0-d78a-59cb-a736-aa8f22c394de"
          },
          {
            "name": "% Conforme 30d",
            "expression": "VAR Fim = CALCULATE(MAX('Painel'[Data]), ALL('Painel')) VAR Conf = CALCULATE([Valor Total], ALL('Painel'), 'Painel'[Data] >= Fim - 29, 'Painel'[Data] <= Fim, 'Painel'[Status] = \"CONFORME\") RETURN DIVIDE(Conf, [Valor Coberto 30d])",
            "formatString": "0.0%",
            "lineageTag": "3ea90a08-8048-5952-91e3-8f9238923153"
          },
          {
            "name": "% Abaixo 30d",
            "expression": "VAR Fim = CALCULATE(MAX('Painel'[Data]), ALL('Painel')) VAR Ab = CALCULATE([Valor Total], ALL('Painel'), 'Painel'[Data] >= Fim - 29, 'Painel'[Data] <= Fim, 'Painel'[Status] = \"ABAIXO DO ACORDO\") RETURN DIVIDE(Ab, [Valor Coberto 30d])",
            "formatString": "0.0%",
            "lineageTag": "eb4d18d6-6e2a-5ed9-b62f-0c8d1fddca7e"
          },
          {
            "name": "Excedente Acima 30d",
            "expression": "VAR Fim = CALCULATE(MAX('Painel'[Data]), ALL('Painel')) RETURN CALCULATE(SUM('Painel'[Diferenca Total]), ALL('Painel'), 'Painel'[Data] >= Fim - 29, 'Painel'[Data] <= Fim, 'Painel'[Status] = \"ACIMA DO ACORDO\")",
            "formatString": "\"R$\" #,0.00",
            "lineageTag": "4b1604ec-e540-59da-99fe-6def5c651e12"
          },
          {
            "name": "Valor Total Ano Anterior",
            "expression": "VAR A = MAX('Painel'[Ano]) RETURN CALCULATE([Valor Total], ALL('Painel'[Ano]), 'Painel'[Ano] = A - 1)",
            "formatString": "\"R$\" #,0.00",
            "lineageTag": "eaf015b7-903b-537e-8343-46f99d7fe02e"
          }
        ],
        "partitions": [
          {
            "name": "Painel",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Parquet.Document(File.Contents(\"C:\\Projetos\\supply-vision\\painel\\consolidado\\supply_vision_painel.parquet\")),",
                "    Tipos = Table.TransformColumnTypes(Fonte, {{\"Data\", type date}}),",
                "    ComAno = Table.AddColumn(Tipos, \"Ano\", each Date.Year([Data]), Int64.Type),",
                "    ComAnoMes = Table.AddColumn(ComAno, \"Ano-Mes\", each Date.ToText([Data], [Format=\"yyyy-MM\"]), type text),",
                "    ComMes = Table.AddColumn(ComAnoMes, \"Mes\", each Date.ToText([Data], [Format=\"MMM/yy\", Culture=\"pt-BR\"]), type text),",
                "    ComMesNum = Table.AddColumn(ComMes, \"Mes Num\", each Date.Month([Data]), Int64.Type),",
                "    ComMesNome = Table.AddColumn(ComMesNum, \"Mes Nome\", each Date.ToText([Data], [Format=\"MMMM\", Culture=\"pt-BR\"]), type text),",
                "    ComTrimestre = Table.AddColumn(ComMesNome, \"Trimestre\", each \"T\" & Text.From(Date.QuarterOfYear([Data])) & \"/\" & Text.From(Date.Year([Data])), type text),",
                "    // Janela de 30 dias ancorada na data mais recente da BASE, nao em",
                "    // DateTime.LocalNow(): assim a pagina de conformidade e as medidas de 30",
                "    // dias usam exatamente o mesmo recorte, e um refresh atrasado nao esvazia",
                "    // a pagina -- ela passa a mostrar os ultimos 30 dias que existem no dado.",
                "    Fim = List.Max(ComTrimestre[Data]),",
                "    ComJanela = Table.AddColumn(ComTrimestre, \"Ultimos 30 dias\", each [Data] >= Date.AddDays(Fim, -29), type logical),",
                "    // 365 dias para a fuga de contrato: sem vigencia na ACORDOS.xlsx, uma",
                "    // compra de 2025 que hoje casa com um acordo pode nao ter tido acordo",
                "    // naquela data. Um ano limita o quanto o catalogo de acordos mudou.",
                "    ComJanelaAno = Table.AddColumn(ComJanela, \"Ultimos 365 dias\", each [Data] >= Date.AddDays(Fim, -364), type logical)",
                "in",
                "    ComJanelaAno"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_21937a3c-adac-4f15-8780-c5ef53d60da1",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f8dde2cd-998e-438f-b8c3-de6c86749d87",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "99cd06c6-d25a-43c3-a1e6-1e121e103175",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ca654763-9c30-4dec-a286-f0d3e2d2bc18",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "7ec69b0c-8e51-445a-8fae-21c8bca08ad2",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8700ebab-93ba-4cb5-aff0-d924124f01bc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "d9b3db9c-82c5-4b83-9cf1-97a691494429",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6661891d-4f9f-4084-8c9e-be91dc34c1d6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "e05312ed-9533-4833-bcb5-570b9a0c64ae",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "0d1f7c8f-4986-498a-862a-1a4ba978673f",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "0e83c383-76ab-452f-a09c-9f6cd905ccc2",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "06ffb7c6-ffb6-4584-8b88-917815db5fcc",
                "ordinal": 3
              }
            ],
            "lineageTag": "22e348bf-447b-43c4-bdc5-78e4f319ce1c"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "d99f4d7d-b0f2-45fd-af6c-19ef27c7c0ce",
        "partitions": [
          {
            "name": "DateTableTemplate_21937a3c-adac-4f15-8780-c5ef53d60da1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_e147814c-e9aa-4a3c-9e3d-9b87ada1b76c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4f87d872-0cbf-4cdd-a9f0-dc82b4a46584",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5c984f1b-7b07-4d30-85cc-eaa8c5d15177",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d6b76d25-5d83-462a-9e1b-8deff56f893d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d6d1a9d0-3bc5-4c55-a2a0-3e2e47bc7d8c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bac918cb-0233-45db-b83b-7c5cdf4b96a2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "3e24303c-5811-4ec0-83cd-6f51b92a6e7f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bbe29715-4e29-435b-a7d5-29c78891ef62",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "7a7983f2-57f2-4f9b-8441-f096af50024e",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "dae52229-c620-42cf-b46e-370cd435c875",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "fb81ebc9-617d-4894-8acf-3440fb68ef4c",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "c1349ff2-ad9f-4f8e-89ec-893420928706",
                "ordinal": 3
              }
            ],
            "lineageTag": "e5a365a3-e135-482f-85c8-f6cf0a3bbe37"
          }
        ],
        "isHidden": true,
        "lineageTag": "2fd20da9-ee06-44f2-83fe-0315f1455bb3",
        "partitions": [
          {
            "name": "LocalDateTable_e147814c-e9aa-4a3c-9e3d-9b87ada1b76c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Painel'[Data])), 1, 1), Date(Year(MAX('Painel'[Data])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_e2659a95-d933-433a-b43d-737ef1a03d8f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "86a624f3-efcd-48f2-a100-57cd51211c9c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0819bf14-9346-49f0-9375-307fbfb77be7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "13d471df-00c3-4a7e-b711-88775710a83e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "45064ea8-7b2f-4b0e-9e7e-c15d626b8c74",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "35dc0dce-5709-4007-90a2-998fe18d19a3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "1c5c0a24-fbfc-4496-95a4-c57e42026e4c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4b246b36-1e75-482f-b18e-418552a135b2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "3f08f94d-4682-4ca6-aa30-c8b7c3ef85fc",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "5a06566f-36e2-4364-820a-185450fd44b2",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "c370fb26-eb7c-40f7-9622-bf5a98b651d6",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "5be4caf3-abde-4bd2-9d0b-f88c5e548a2d",
                "ordinal": 3
              }
            ],
            "lineageTag": "5352d2a6-8fa6-4d15-befa-893cd104b512"
          }
        ],
        "isHidden": true,
        "lineageTag": "ef721d46-8db1-4bf5-9301-6a6a8aa63e54",
        "partitions": [
          {
            "name": "LocalDateTable_e2659a95-d933-433a-b43d-737ef1a03d8f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Painel'[DATA_EXECUCAO])), 1, 1), Date(Year(MAX('Painel'[DATA_EXECUCAO])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}